version: "3.8"

services:
  db:
    container_name: "workoutDB"
    image: postgres:12.4-alpine
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "5433:5432"
    volumes:
      - "./database/postgres-data:/var/lib/postgresql/data:rw"
    restart: unless-stopped